---
trigger:
  branches:
    include:
      - main

parameters:
  - name: skip_what_if
    displayName: 'Skip What If Check?'
    type: boolean
    default: true
  - name: governance-int-root
    displayName: 'Run Step: Governance-Intermediate Root'
    type: boolean
    default: true
  - name: governance-landingzones
    displayName: 'Run Step: Governance-Landing Zones'
    type: boolean
    default: true
  - name: governance-landingzones-corp
    displayName: 'Run Step: Governance-Landing Zones Corp'
    type: boolean
    default: true
  - name: governance-landingzones-online
    displayName: 'Run Step: Governance-Landing Zones Online'
    type: boolean
    default: true
  - name: governance-landingzones-local
    displayName: 'Run Step: Governance-Landing Zones Local'
    type: boolean
    default: true
  - name: governance-platform
    displayName: 'Run Step: Governance-Platform'
    type: boolean
    default: true
  - name: governance-platform-connectivity
    displayName: 'Run Step: Governance-Platform Connectivity'
    type: boolean
    default: true
  - name: governance-platform-identity
    displayName: 'Run Step: Governance-Platform Identity'
    type: boolean
    default: true
  - name: governance-platform-management
    displayName: 'Run Step: Governance-Platform Management'
    type: boolean
    default: true
  - name: governance-platform-security
    displayName: 'Run Step: Governance-Platform Security'
    type: boolean
    default: true
  - name: governance-sandbox
    displayName: 'Run Step: Governance-Sandbox'
    type: boolean
    default: true
  - name: governance-decommissioned
    displayName: 'Run Step: Governance-Decommissioned'
    type: boolean
    default: true
  - name: governance-platform-rbac
    displayName: 'Run Step: Governance-Platform RBAC'
    type: boolean
    default: true
  - name: governance-platform-connectivity-rbac
    displayName: 'Run Step: Governance-Platform Connectivity RBAC'
    type: boolean
    default: true
  - name: governance-landingzones-rbac
    displayName: 'Run Step: Governance-Landing Zones RBAC'
    type: boolean
    default: true
  - name: core-logging
    displayName: 'Run Step: Core-Logging'
    type: boolean
    default: true
  - name: networking-hubnetworking
    displayName: 'Run Step: Networking-Hub Networking'
    type: boolean
    default: true

resources:
  repositories:
    - repository: templates
      type: git
      name: Azure Landing Zone/alz-mgmt-templates

lockBehavior: sequential

extends:
  template: .pipelines/cd-template.yaml@templates
  parameters:
    skip_what_if: ${{ parameters.skip_what_if }}
    governance-int-root: ${{ parameters['governance-int-root'] }}
    governance-landingzones: ${{ parameters['governance-landingzones'] }}
    governance-landingzones-corp: ${{ parameters['governance-landingzones-corp'] }}
    governance-landingzones-online: ${{ parameters['governance-landingzones-online'] }}
    governance-landingzones-local: ${{ parameters['governance-landingzones-local'] }}
    governance-platform: ${{ parameters['governance-platform'] }}
    governance-platform-connectivity: ${{ parameters['governance-platform-connectivity'] }}
    governance-platform-identity: ${{ parameters['governance-platform-identity'] }}
    governance-platform-management: ${{ parameters['governance-platform-management'] }}
    governance-platform-security: ${{ parameters['governance-platform-security'] }}
    governance-sandbox: ${{ parameters['governance-sandbox'] }}
    governance-decommissioned: ${{ parameters['governance-decommissioned'] }}
    governance-platform-rbac: ${{ parameters['governance-platform-rbac'] }}
    governance-platform-connectivity-rbac: ${{ parameters['governance-platform-connectivity-rbac'] }}
    governance-landingzones-rbac: ${{ parameters['governance-landingzones-rbac'] }}
    core-logging: ${{ parameters['core-logging'] }}
    networking-hubnetworking: ${{ parameters['networking-hubnetworking'] }}
